/* Read-only Backstage catalog adapter. No GitHub/repository configuration is imported. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BackstageCore=api})(globalThis,()=>{
'use strict';
const relationTypes={dependsOn:{inverse:'dependencyOf',label:'Depende de',color:'purple'},providesApi:{inverse:'apiProvidedBy',label:'Fornece API',color:'green'},consumesApi:{inverse:'apiConsumedBy',label:'Consome API',color:'blue'},partOf:{inverse:'hasPart',label:'Faz parte de',color:'gray'},ownedBy:{inverse:'ownerOf',label:'Responsável',color:'amber'},childOf:{inverse:'parentOf',label:'Filho de',color:'gray'},memberOf:{inverse:'hasMember',label:'Membro de',color:'gray'}};
const defaults={schemaVersion:1,catalogBaseUrl:'',webBaseUrl:'',kinds:['Domain','System','Component','API','Resource','Template','Group'],pageSize:100};
const clone=o=>JSON.parse(JSON.stringify(o));
function ref(value){if(typeof value!=='string')throw Error('Referência de entidade inválida.');const m=/^([a-zA-Z][a-zA-Z0-9]*):([a-zA-Z0-9_.-]+)\/([a-zA-Z0-9_.-]+)$/.exec(value);if(!m)throw Error('Use kind:namespace/name: '+value.slice(0,120));return value.toLowerCase()}
function entityRef(entity){if(!entity||typeof entity.kind!=='string'||!entity.metadata||typeof entity.metadata.name!=='string')throw Error('Entidade sem kind ou metadata.name.');return ref(`${entity.kind}:${entity.metadata.namespace||'default'}/${entity.metadata.name}`)}
function validUrl(value){if(value==='')return '';const u=new URL(value);if(u.username||u.password||u.search||u.hash||!(u.protocol==='https:'||(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname))))throw Error('Use HTTPS, ou HTTP local, sem credenciais ou parâmetros.');return u.href.replace(/\/$/,'')}
function validate(raw){if(!raw||raw.schemaVersion!==1)throw Error('schemaVersion deve ser 1.');if(typeof raw.catalogBaseUrl!=='string'||typeof raw.webBaseUrl!=='string')throw Error('Informe as URLs do catálogo e do portal.');if(!Array.isArray(raw.kinds)||!raw.kinds.length||raw.kinds.length>30||raw.kinds.some(k=>typeof k!=='string'||!/^[a-zA-Z][a-zA-Z0-9]*$/.test(k)))throw Error('Informe pelo menos um kind válido.');if(!Number.isInteger(raw.pageSize)||raw.pageSize<1||raw.pageSize>500)throw Error('pageSize deve ficar entre 1 e 500.');return {schemaVersion:1,catalogBaseUrl:validUrl(raw.catalogBaseUrl),webBaseUrl:validUrl(raw.webBaseUrl),kinds:[...new Set(raw.kinds)],pageSize:raw.pageSize}}
function normalize(entities){if(!Array.isArray(entities)||entities.length>50000)throw Error('Informe uma lista de até 50.000 entidades.');const map=new Map(),edges=new Map(),warnings=[],originals=new Map();
 for(const entity of entities){const key=entityRef(entity);if(map.has(key))throw Error('Entidade duplicada: '+key);if(entity.relations!==undefined&&!Array.isArray(entity.relations))throw Error('relations deve ser uma lista em '+key);const namespace=key.split(':')[1].split('/')[0];map.set(key,{ref:key,name:entity.metadata.name,title:typeof entity.metadata.title==='string'?entity.metadata.title:entity.metadata.name,kind:entity.kind,namespace,description:typeof entity.metadata.description==='string'?entity.metadata.description:'',type:typeof entity.spec?.type==='string'?entity.spec.type:'',lifecycle:typeof entity.spec?.lifecycle==='string'?entity.spec.lifecycle:'',missing:false});originals.set(key,clone(entity));}
 for(const entity of entities){const source=entityRef(entity);if(!entity.relations?.length&&entity.spec&&['dependsOn','providesApis','consumesApis','owner','system','domain'].some(k=>entity.spec[k]!==undefined))warnings.push(`${source}: há declarações em spec, mas nenhuma relação processada foi fornecida.`);for(const r of entity.relations||[]){if(!r||typeof r.type!=='string'||!r.type||r.type.length>100)throw Error('Tipo de relação inválido em '+source);const target=ref(r.targetRef);let type=r.type,from=source,to=target;const inverse=Object.entries(relationTypes).find(([,v])=>v.inverse===r.type);if(inverse){type=inverse[0];from=target;to=source}const key=JSON.stringify([from,type,to]);if(!edges.has(key))edges.set(key,{id:key,from,to,type,evidence:[]});edges.get(key).evidence.push({entityRef:source,type:r.type,targetRef:target});if(!map.has(target)){const [kind,path]=target.split(':'),[namespace,name]=path.split('/');map.set(target,{ref:target,name,title:name,kind,namespace,missing:true,description:'Referência fora do escopo ou não carregada; existência não verificada.',type:'',lifecycle:''})}}}
 const nodes=[...map.values()].sort((a,b)=>a.ref.localeCompare(b.ref));for(const n of nodes)if(n.missing)warnings.push(`${n.ref}: fora do escopo ou não carregada.`);
 return {nodes,edges:[...edges.values()],warnings,entities:[...originals.values()]};
}
// Only dependsOn participates in dependency impact. Ownership and containment aren't runtime dependencies.
function impact(graph,key,direction='dependencies'){key=ref(key);const adjacency=new Map(graph.nodes.map(n=>[n.ref,[]]));for(const e of graph.edges)if(e.type==='dependsOn'){const from=direction==='consumers'?e.to:e.from,to=direction==='consumers'?e.from:e.to;adjacency.get(from)?.push(to)}const seen=new Set([key]),queue=[key];for(let i=0;i<queue.length;i++)for(const next of adjacency.get(queue[i])||[])if(!seen.has(next)){seen.add(next);queue.push(next)}seen.delete(key);return [...seen].sort()}
async function discover(raw,{token='',fetchImpl=fetch,onProgress=()=>{}}={}){const config=validate(raw);if(!config.catalogBaseUrl)throw Error('Configure a URL da API do catálogo.');const all=[],seenCursors=new Set();let cursor=null;for(let page=1;page<=1000;page++){const params=new URLSearchParams();if(cursor)params.set('cursor',cursor);else{params.set('limit',String(config.pageSize));config.kinds.forEach(kind=>params.append('filter','kind='+kind))}onProgress(`Consultando catálogo · página ${page}`);let response;try{response=await fetchImpl(config.catalogBaseUrl+'/entities/by-query?'+params,{headers:{Accept:'application/json',...(token?{Authorization:'Bearer '+token}:{})},redirect:'error',signal:AbortSignal.timeout(30000)})}catch{throw Error('Falha de conexão. Verifique a URL do catálogo, a rede e a política CORS.')}if(!response.ok)throw Error(response.status===401||response.status===403?'Acesso ao catálogo não autorizado. Verifique a credencial e as permissões.':`Catálogo retornou HTTP ${response.status}.`);const data=await response.json();if(!data||!Array.isArray(data.items))throw Error('Resposta inválida: esperado items da API /entities/by-query.');all.push(...data.items);if(all.length>50000)throw Error('Limite de 50.000 entidades excedido; nenhum snapshot parcial será publicado.');cursor=data.pageInfo?.nextCursor;if(cursor===undefined||cursor===null||cursor==='')return {...normalize(all),source:'backstage',syncedAt:new Date().toISOString()};if(typeof cursor!=='string'||seenCursors.has(cursor))throw Error('Cursor inválido ou repetido; coleta interrompida.');seenCursors.add(cursor)}throw Error('Limite de paginação atingido; consulta incompleta.')}
return {defaults,clone,ref,entityRef,validate,normalize,impact,discover,relationTypes};
});
