const {test}=require('node:test');
const assert=require('node:assert/strict');
const C=require('../core.js');
const metric=(value,quality='Medido')=>({value,quality});
function record(){return {hours:metric(10),saving:metric(0),cost:metric(null),tokens:metric(250,'Estimado'),evidence:'Apontamento manual'};}
function base(){const data=C.initial();data.items.push({id:'one',name:'Triagem',description:'Apoia a triagem',areas:['Redes','Cloud'],kind:'',status:'Em uso',owner:'Equipe',architecture:'Alertas → análise',model:'',links:[],metrics:{'2025-01':record()},custom:{},updated:'25/09/2026'});return data;}
test('base inicial vazia, tipo opcional e múltiplas áreas',()=>{assert.equal(C.initial().items.length,0);assert.equal(C.validate(base()).items[0].kind,'');assert.equal(C.validate(base()).items[0].areas.length,2);});
test('indicadores distinguem zero, vazio e estimativas no período correto',()=>{const data=base();const totals=C.summarize(data.items,'2025-01','Medido');assert.deepEqual(totals.saving,{sum:0,count:1,filled:1,measured:1,estimated:0});assert.equal(totals.cost.count,0);assert.equal(totals.tokens.count,0);assert.equal(totals.tokens.filled,1);assert.equal(C.summarize(data.items,'2024-12').hours.count,0);});
test('registros de meses diferentes são preservados e revisões obsoletas rejeitadas',()=>{const old=base(),next=structuredClone(old);next.items[0].metrics['2024-05']=record();const saved=C.revise(old,next);assert.equal(saved.revision,1);assert.deepEqual(Object.keys(saved.items[0].metrics),['2025-01','2024-05']);assert.throws(()=>C.revise(saved,next),e=>e.status===409);});
test('não exclui categorias em uso, mas permite arquivar e remover tipo da iniciativa',()=>{const data=base();data.areas.find(x=>x.name==='Cloud').active=false;assert.doesNotThrow(()=>C.validate(data));data.areas=data.areas.filter(x=>x.name!=='Cloud');assert.throws(()=>C.validate(data),/Área não cadastrada/);});
test('rejeita períodos inválidos, valores negativos e tokens fracionados',()=>{for(const [key,value] of [['hours',-1],['tokens',1.5],['cost',Infinity]]){const data=base();data.items[0].metrics['2025-01'][key].value=value;assert.throws(()=>C.validate(data));}const data=base();data.items[0].metrics['2025-13']=record();assert.throws(()=>C.validate(data),/Período/);});
test('links executáveis e tipos desconhecidos não entram na base',()=>{const data=base();data.items[0].links=[{type:'Outro',title:'Teste',url:'javascript:alert(1)'}];assert.throws(()=>C.validate(data),/HTTP/);data.items[0].links=[];data.items[0].kind='Ausente';assert.throws(()=>C.validate(data),/Tipo não cadastrado/);});
test('campos personalizados validam valores e identificadores',()=>{const data=base();data.extraFields=[{id:'deadline',name:'Data',type:'date',show:true}];data.items[0].custom.deadline='2026-02-30';assert.throws(()=>C.validate(data),/data inválida/);data.items[0].custom.deadline='2026-02-28';assert.doesNotThrow(()=>C.validate(data));data.extraFields[0].id='__proto__';assert.throws(()=>C.validate(data),/Identificador/);});
test('impede duplicação de nomes, IDs e áreas',()=>{const data=base();data.kinds.push({name:'agente',active:true});assert.throws(()=>C.validate(data),/duplicados/);const other=base();other.items.push(structuredClone(other.items[0]));assert.throws(()=>C.validate(other),/duplicados/);});
