import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {once} from 'node:events';
import {createService,projectRoot} from '../server.mjs';
async function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-initiatives-'));const file=path.join(dir,'iniciativas.json');const server=createService({file});server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));fs.rmSync(dir,{recursive:true,force:true});});return {file,server,origin,get:()=>fetch(origin+'/api/initiatives'),put:(data,headers={})=>fetch(origin+'/api/initiatives',{method:'PUT',headers:{'Content-Type':'application/json',Origin:origin,...headers},body:JSON.stringify(data)})};}
test('salva de verdade, preserva backup e relê após reinício',async t=>{const f=await fixture(t),initial=await (await f.get()).json();initial.kinds.push({name:'Teste',active:true});const response=await f.put(initial);assert.equal(response.status,200);const saved=await response.json();assert.equal(saved.revision,1);assert.equal(JSON.parse(fs.readFileSync(f.file+'.bak')).revision,0);assert.equal(JSON.parse(fs.readFileSync(f.file)).kinds.at(-1).name,'Teste');const other=createService({file:f.file});other.listen(0,'127.0.0.1');await once(other,'listening');try{assert.equal((await (await fetch(`http://127.0.0.1:${other.address().port}/api/initiatives`)).json()).revision,1);}finally{other.closeAllConnections();await new Promise(resolve=>other.close(resolve));}});
test('duas gravações concorrentes aceitam uma e recusam outra',async t=>{const f=await fixture(t),base=await (await f.get()).json();const [a,b]=await Promise.all([f.put(base),f.put(base)]);assert.deepEqual([a.status,b.status].sort(),[200,409]);assert.equal((await (await f.get()).json()).revision,1);});
test('validação, origem e lock preservam arquivo original',async t=>{const f=await fixture(t),base=await (await f.get()).json(),before=fs.readFileSync(f.file,'utf8');const invalid={...base,kinds:null};assert.equal((await f.put(invalid)).status,422);assert.equal((await f.put(base,{Origin:'https://example.com'})).status,403);fs.writeFileSync(f.file+'.lock','test');assert.equal((await f.put(base)).status,423);assert.equal(fs.readFileSync(f.file,'utf8'),before);assert.equal(fs.existsSync(f.file+'.bak'),false);});
test('servidor entrega o módulo e bloqueia dados privados e caminhos ocultos',async t=>{const f=await fixture(t);assert.equal((await fetch(f.origin+'/modules/initiatives/')).status,200);assert.equal((await fetch(f.origin+'/modules/initiatives/data/iniciativas.json')).status,403);assert.equal((await fetch(f.origin+'/.git/config')).status,403);assert.equal((await fetch(f.origin+'/management/backlog/data.json')).status,403);assert.equal((await fetch(f.origin+'/api/other')).status,404);assert.equal((await fetch(f.origin+'/index.html',{method:'POST'})).status,405);});
test('base corrompida não é reinicializada silenciosamente',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-corrupt-'));try{const file=path.join(dir,'data.json');fs.writeFileSync(file,'broken');assert.throws(()=>createService({root:projectRoot,file}));assert.equal(fs.readFileSync(file,'utf8'),'broken');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
