const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../core.js');
const config=()=>{const c=C.clone(C.defaults);c.github.organization='example';return c};
const response=(data,status=200)=>({ok:status===200,status,headers:{get:()=>null},json:async()=>data});
test('rules are anchored, escaped and case-insensitive; exact names override',()=>{const c=config();assert(C.matches('ATLAS-terraform-rds','atlas-terraform-*'));assert(!C.matches('prefix-atlas-terraform-rds','atlas-terraform-*'));assert(!C.matches('atlasXfoo','atlas.foo'));assert.equal(C.category('atlas-frontend',c),'Frontend');c.exclude=['atlas-frontend'];assert(!C.selected({name:'atlas-frontend'},c));assert(!C.selected({name:'atlas',archived:true},c))});
test('stable versions compare numerically, refs and ranges remain unknown',()=>{assert.equal(C.latest(['v1.9.0','v1.10.0','v2.0.0-beta','latest']), 'v1.10.0');assert.equal(C.status('1.10.0','v1.10.0'),'current');assert.equal(C.status('v2.0.0','v1.0.0'),'ahead');assert.equal(C.status('^1.0.0','v2.0.0'),'unknown');assert.equal(C.status('main',null),'unknown');assert.equal(C.latest(['v01.0.0']),null)});
test('invalid configuration rejected and credentials removed',()=>{const c=config();c.token='secret';assert(!('token' in C.validate(c)));c.dependencies.push({...c.dependencies[0]});assert.throws(()=>C.validate(c),/duplicadas/);c.dependencies=[];c.github.apiBase='https://user:pass@api.github.com';assert.throws(()=>C.validate(c),/credenciais/)});
test('discovery paginates organization and tags; explicit repos and dependencies included',async()=>{const c=config();c.repositories=[{name:'special',category:'Outro'}];c.dependencies=[{from:'special',to:'external',version:'v1.0.0',file:'x.yml'}];const calls=[];const fetchImpl=async(url,options)=>{calls.push(url);assert.equal(options.headers.Authorization,'Bearer temporary');assert(url.startsWith('https://api.github.com/'));if(url.includes('/orgs/'))return response(url.includes('page=2')?[{name:'atlas-template-rds'}]:Array.from({length:100},(_,i)=>({name:'unmatched-'+i})));if(url.includes('/tags'))return response(url.includes('page=2')?[{name:'v9.0.0'}]:Array.from({length:100},(_,i)=>({name:'v1.0.'+i})));return response({name:url.split('/').pop()})};const result=await C.discover(c,{token:'temporary',fetchImpl});assert.deepEqual(result.repos.map(r=>r.name),['atlas-template-rds','external','special']);assert(result.repos.every(r=>r.latest==='v9.0.0'));assert(calls.some(u=>u.includes('/orgs/')&&u.includes('page=2')));assert.equal(result.warnings.length,0);assert(!JSON.stringify(result).includes('temporary'))});
test('organization errors fail atomically; tag errors yield unknown version with warning',async()=>{const c=config();c.repositories=[];c.dependencies=[];await assert.rejects(C.discover(c,{fetchImpl:async()=>response({},401)}),/Token/);const r=await C.discover(c,{fetchImpl:async url=>url.includes('/orgs/')?response([{name:'atlas-terraform-rds'}]):response({},403)});assert.equal(r.repos[0].latest,null);assert.equal(r.warnings.length,1)});
test('no stable tags and excluded dependencies never become false current results',async()=>{const c=config();c.repositories=[];c.dependencies=[];c.exclude=['atlas-template-rds'];const r=await C.discover(c,{fetchImpl:async url=>response(url.includes('/orgs/')?[{name:'atlas-template-rds'},{name:'atlas-terraform-rds'}]:[{name:'nightly'}])});assert.equal(r.repos.length,1);assert.equal(C.status('v1.0.0',r.repos[0].latest),'unknown')});
